---
title: "Untitled"
output: github_document
date: "2025-10-02"
---
```{r}
library(tidyverse)
library(p8105.datasets)
data("weather_df")
```

```{r}
weather_df = 
  weather_df |>
  mutate(
    month = floor_date(date, unit = "month"))
weather_df
```

```{r}
weather_df = 
  weather_df |>
  mutate(
    month = lubridate::floor_date(date, unit = "month"))
weather_df
```

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp >= 1000)
```

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```

```{r}
weather_df |>
  group_by(name, month)
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n())
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())
```

```{r}
weather_df |>
  count(name)
```

```{r}
weather_df |>
  count(month, name = "n_obs")
```

```{r}
weather_df |>
  pull(month) |> 
  table()
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) |> 
  filter(name != "Molokai_HI") |> 
  group_by(name, cold) |> 
  summarize(count = n())
```

```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE     ~ ""
  )) |> 
  filter(name != "Molokai_HI") |> 
  janitor::tabyl(name, cold)
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(across(tmin:prcp, mean))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) |> 
  knitr::kable(digits = 1)
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |> 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_ranking = min_rank(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(tmax) < 2)
```

```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(desc(tmax)) < 4)
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax))
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax)) |>
  summarize(
    temp_change_sd = sd(temp_change, na.rm = TRUE),
    temp_change_max = max(temp_change, na.rm = TRUE))
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax),
         change_rank = min_rank(desc(temp_change))) |>
  filter(
    change_rank <2
         )
```

